import xgi
import numpy as np
import math
import scipy.special as ss
# from collections import Counter

class EM:
    
    def __init__(self, edge_sample_likelihood, nodes_from_hypergraph_likelihood, novel_nodes_likelihood):
        """
        Start with the non-gauranteed version and move on. 
        """
        self.ll_history = []
        
        self.edge_sample_likelihood  =  edge_sample_likelihood
        self.nodes_from_hypergraph_likelihood = nodes_from_hypergraph_likelihood
        self.novel_nodes_likelihood = novel_nodes_likelihood
        
    def fit(self, H, pars = None, max_iter = 100, tol = 1e-6):
        # self.e_vec, self.H_vec = H.e_vecs, H.H_vecs
        # self.H = H
        
        # initial guess, if not given then start with a default guess.
        if pars:
            self.pars = pars
        else:   
            self.pars = 0.1, 0.05, 3

        self.form_arrays(H)
        
        self.ll_history.append(self.marginal_log_likelihood(H))
        done = False
        i = 0
        while not done: 
            self.E_step(H)
            self.M_step(H)
            self.ll_history.append(self.marginal_log_likelihood(H))
            if (self.ll_history[-1] - self.ll_history[-2] < tol) or i > max_iter:
                done = True
            i += 1
    
    def form_arrays(self, H):
        """
        There are a number of arrays with hyperedge topology that need to be formed. 
        This function forms and stores these arrays for future use in the E-step and M-step. 
        
        THIS FUNCTION IS A PRIME SOURCE OF LIKELY BUGS
        Lots of checks needed
        """
        
        self.edge_sizes = H.edge_size_sequence()
        
        # not totally sure what these are doing or even where they come from? 
        # want to eventually change out this functionality here so that the hypergraph class has a lot less baggage it needs to store. 
        node_counts = []
        nodes = set()
        for x in xgi.to_hyperedge_list(H.H):
            nodes = nodes.union(x)
            node_counts.append(len(nodes))
        
        self.node_counts = np.array(node_counts)
        self.edge_counts = np.arange(1, len(xgi.to_hyperedge_list(H.H)))
        
        
        # sizes of intersections
        # entry [i, j] is the size of the intersection between edge i and edge j, PROVIDED i > j (as in this case i can be generated by j) 
        IX = xgi.intersection_profile(H.H).toarray()
        IX = np.tril(IX) # Xie is correct that this should be lower triangular
        np.fill_diagonal(IX, 0) 
        self.intersection_sizes = IX
        
        # number of novel nodes per new edge
        novel_node_vec = []
        seen = set()
        for e in H.H.edges.members():
            novel_node_vec.append(len(e.difference(seen)))
            seen = seen.union(e)
            
        self.num_novel_nodes = np.array(novel_node_vec)
        
        # number of nodes from hypergraph added per new edge, depending on which old edge was sampled
        # entry [i, j] is the number of nodes that must have been added to form i if j was sampled 
        
        other_nodes_mat = (self.edge_sizes - self.num_novel_nodes)[:,np.newaxis] - self.intersection_sizes
        other_nodes_mat = np.tril(other_nodes_mat) 
        np.fill_diagonal(other_nodes_mat, 0) 
        self.other_nodes = other_nodes_mat
                
    def E_step(self):
        """
        form the matrix CHI of edge generation probabilities 
        CHI[i, j] is the probability that edge i was sampled from edge j
        rows need to sum to 1
        should be lower triangular
        """
        
        s1 = self.edge_sample_likelihood(selected     = self.intersection_sizes,
                                         total        = self.edge_sizes[np.newaxis,:], 
                                         eta          = self.pars["eta"])
        
        s2 = self.novel_nodes_likelihood(self.num_novel_nodes, beta = self.pars["beta"])
        
        s3 = self.nodes_from_hypergraph_likelihood(self.other_nodes, gamma = self.pars["gamma"])
        
        s3 = s3*self.node_counts[:,np.newaxis]**(-1.0*self.other_nodes)
        
        self.s1  = s1
        self.s2  = s2
        self.s3  = s3
        self.CHI = s1*s2*s3
        # *s2*s3
        
        ix = self.CHI.sum(axis = 1) == 0  
        self.CHI[ix,:] = np.eye(self.CHI.shape[0])[ix,:]
        
        self.CHI = (self.CHI / self.CHI.sum(axis = 1)[:, np.newaxis])
    
    def M_step(self):
        
        self.pars["eta"] = self.edge_sample_likelihood.m_step(self.intersection_sizes, self.edge_sizes[np.newaxis,:], self.CHI)
        
        self.pars["beta"] = self.novel_nodes_likelihood.m_step(self.num_novel_nodes, self.CHI)
        
        self.pars["gamma"] = self.nodes_from_hypergraph_likelihood.m_step(self.other_nodes, self.CHI)
        
        
        
        
        
################################################################################
################################################################################
################################################################################




############# 
# Likelihoods
############# 

class Likelihood:
    
    def __init__(self, pmf, m_step):
        
        self.pmf = pmf 
        self.m_step = m_step
    
class EdgeSampleLikelihood(Likelihood):
    
    def __call__(self, selected, total, **pars):
        
        L = self.pmf(selected, total, **pars) 
        L = np.tril(L)
        np.fill_diagonal(L, 0)
        return L

    def m_step(self, selected, total, chi):
        
        return self.m_step(selected, total, chi)        
        
class NovelNodesLikelihood(Likelihood):
    
    def __call__(self, num_novel_nodes, **pars):
        
        L = self.pmf(num_novel_nodes, **pars)
        return np.tril(L) 
    
    def m_step(self, num_novel_nodes, chi):
        return self.m_step(num_novel_nodes, chi)
    
class NodesFromHypergraphLikelihood(Likelihood): 
    
    def __call__(self, num_nodes_to_add, **pars):
        # need to check this
        L = self.pmf(num_nodes_to_add, **pars)
        return np.tril(L)
    
    def m_step(self, num_nodes_to_add, chi):
        return self.m_step(num_nodes_to_add, chi)
