import xgi
import numpy as np
import math
import scipy.special as ss


class EM:
    
    def __init__(self, edge_sample_likelihood, nodes_from_hypergraph_likelihood, novel_nodes_likelihood):
        """
        Start with the non-gauranteed version and move on. 
        """
        self.ll_history = []
        
        self.edge_sample_likelihood  =  edge_sample_likelihood
        self.nodes_from_hypergraph_likelihood = nodes_from_hypergraph_likelihood
        self.novel_nodes_likelihood = novel_nodes_likelihood
        
    def fit(self, H, pars = None, max_iter = 100, tol = 1e-6):
        """
        main loop: initializes parameters and arrays encoding 
        topology, then alternates E and M steps until convergence
        """
        
        # initial guess, if not given then start with a default guess.
        if pars:
            self.pars = pars
        else:   
            self.pars = {"eta" : 0.1, "beta" : 0.1, "gamma" : 0.7}

        # pre-computed for E and M steps
        self.form_arrays(H)
        
        # initialize for main loop
        self.ll_history.append(self.marginal_log_likelihood())
        done = False
        i = 0
        
        self.base_H = H.H
        
        # do EM until convergence
        while not done: 
            self.E_step()
            self.M_step()
            ll = self.marginal_log_likelihood()
            self.ll_history.append(ll)
            print(f"Step {i}: marginal ll = {ll}")
            if (self.ll_history[-1] - self.ll_history[-2] < tol) or i > max_iter:
                done = True
            i += 1
    
    def form_arrays(self, H):
        """
        There are a number of arrays with hyperedge topology that need to be formed. 
        This function forms and stores these arrays for future use in the E-step and M-step. 
        """
        
        # sequences of edge sizes, in order
        self.edge_sizes = H.edge_size_sequence()
        
        # sequence of number of edges in hypergraph (one is added in each timestep)
        # NOTE: might need to modify this if we decide we want to formally allow hypergraphs to init with more than a single edge
        self.edge_counts = np.arange(1, len(xgi.to_hyperedge_list(H.H)))
        
        # sequence of number nodes in hypergraph at each timestep
        # grows in time as nodes get added
        node_counts = []
        self.nodes = set()
        for x in xgi.to_hyperedge_list(H.H):
            self.nodes = self.nodes.union(x)
            node_counts.append(len(self.nodes))
        
        self.node_counts = np.array(node_counts)
        
        # sizes of edge intersections
        # entry [i, j] is the size of the intersection between edge i and edge j, PROVIDED i > j (as in this case i can be generated by j) 
        # as pointed out by Xie, this array and the ones following should be lower-triangular. 
        IX = xgi.intersection_profile(H.H).toarray()
        IX = np.tril(IX) 
        np.fill_diagonal(IX, 0) 
        self.intersection_sizes = IX
        
        # number of novel nodes per new edge
        # NOTE: could this be obtained from node_counts without recalculating, right?
        novel_node_vec = []
        self.seen = set()
        for e in H.H.edges.members():
            novel_node_vec.append(len(e.difference(self.seen)))
            self.seen = self.seen.union(e)
        
        self.num_novel_nodes = np.array(novel_node_vec)
        
        
        # number of nodes from hypergraph added per new edge, depending on which old edge was sampled
        # entry [i, j] is the number of nodes that must have been added to form i if j was sampled 
        other_nodes_mat = (self.edge_sizes - self.num_novel_nodes)[:,np.newaxis] - self.intersection_sizes
        other_nodes_mat = np.tril(other_nodes_mat) 
        np.fill_diagonal(other_nodes_mat, 0) 
        self.other_nodes = other_nodes_mat
 
    


    def marginal_log_likelihood(self):
        """
        Compute the marginal log likelihood with currently stored parameters and arrays
        
        THIS IS THE WRONG API: should allow the user to pass a hypergraph and a set of parameters. That user-facing version should form new arrays and do the calculation. Then there can be an internal version of this function that streamlines and skips the form_arrays method when called in a context where we can guarantee that the arrays are already computed
        """
        s1 = self.edge_sample_likelihood(selected     = self.intersection_sizes,
                                         total        = self.edge_sizes[np.newaxis,:], 
                                         eta          = self.pars["eta"])
        
        s2 = self.novel_nodes_likelihood(self.num_novel_nodes, beta = self.pars["beta"])
        
        s3 = self.nodes_from_hypergraph_likelihood(self.other_nodes, gamma = self.pars["gamma"])
        
        s3 = s3*self.node_counts[:,np.newaxis]**(-1.0*self.other_nodes)
        
        M = s1*s2*s3 
        means = M.sum(axis = 1) / np.arange(1, M.shape[0]+1)
        
        return np.ma.masked_invalid(np.log(means)).sum()
               
    def E_step(self):
        """
        form the matrix CHI of edge generation probabilities 
        CHI[i, j] is the probability that edge i was sampled from edge j
        rows need to sum to 1
        should be lower triangular
        """
        s1 = self.edge_sample_likelihood(selected     = self.intersection_sizes,
                                         total        = self.edge_sizes[np.newaxis,:], 
                                         eta          = self.pars["eta"])
        
        s2 = self.novel_nodes_likelihood(self.num_novel_nodes, beta = self.pars["beta"])
        
        s3 = self.nodes_from_hypergraph_likelihood(self.other_nodes, gamma = self.pars["gamma"])
        
        s3 = s3*self.node_counts[:,np.newaxis]**(-1.0*self.other_nodes)
        
        self.s1  = s1
        self.s2  = s2
        self.s3  = s3
        self.CHI = s1*s2*s3
        # *s2*s3
        
        ix = self.CHI.sum(axis = 1) == 0  
        self.CHI[ix,:] = np.eye(self.CHI.shape[0])[ix,:]
        
        self.CHI = (self.CHI / self.CHI.sum(axis = 1)[:, np.newaxis])
    
    def M_step(self):
        """
        compute parameter estimates based on the current status of th E-step matrix (self.CHI). 
        these estimators are supplied with the likelihood objects passed to the model
        """
        self.pars["eta"] = self.edge_sample_likelihood.m_step(self.intersection_sizes, self.edge_sizes[np.newaxis,:], self.CHI)
        
        self.pars["beta"] = self.novel_nodes_likelihood.m_step(self.num_novel_nodes, self.CHI)
        
        self.pars["gamma"] = self.nodes_from_hypergraph_likelihood.m_step(self.other_nodes, self.CHI)
            
    def predict(self, new_candidate_edges):
        
        new_edge_counts = len(new_candidate_edges)
        H_comp = self.base_H
        base_edges = H_comp.num_edges
        
        H_pred = xgi.Hypergraph()
        H_pred.add_edges_from(new_candidate_edges)
        
        H_comp.add_edges_from(new_candidate_edges)
        
        # sequences of edge sizes, in order
        edge_sizes = H_pred.edges.size.asnumpy()
    
    
        # number of novel edges per every edge in the new list
        novel_node_vec = []
        for e in H_pred.edges.members():
            novel_node_vec.append(len(e.difference(self.seen)))

        num_novel_nodes = np.array(novel_node_vec)
        
        
        # sequence of number nodes in hypergraph at each timestep
        # grows in time as nodes get added
        node_counts = []
        for x in xgi.to_hyperedge_list(H_pred):
            nodes = self.nodes.union(x)
            node_counts.append(len(nodes))
        
        node_counts = np.array(node_counts)
        
        ############## THIS IS THE MAIN DIFFERENCE FROM EVERYTHING ELSE#################
        ############## THIS INCLUDE THE INTERSECTION BETWEEN THE NEW LIST OF EDGES AND OLD LIST OF EDGES###############
        
        IX = xgi.intersection_profile(H_comp).toarray()
        IX = np.tril(IX) 
        np.fill_diagonal(IX, 0) 
        intersection_sizes = IX[-new_edge_counts:, :base_edges].transpose()
        
        
        novel_nodes_mat = np.tile(num_novel_nodes,(base_edges,1))
        edge_sizes_mat = np.tile(edge_sizes,(base_edges,1))
        node_counts_mat = np.tile(node_counts,(base_edges,1))
    
        other_nodes = edge_sizes_mat - novel_nodes_mat - intersection_sizes
        
        #other_nodes = (edge_sizes - num_novel_nodes)[:,np.newaxis] - intersection_sizes
        
        s1 = self.edge_sample_likelihood(selected     = intersection_sizes,
                                         total        = edge_sizes_mat,  
                                         eta          = self.pars["eta"])
        
        s2 = self.novel_nodes_likelihood(novel_nodes_mat, beta = self.pars["beta"])
        
        s3 = self.nodes_from_hypergraph_likelihood(other_nodes, gamma = self.pars["gamma"])
        
        s3 = s3*node_counts_mat**(-1.0*other_nodes)
        
        
        self.PRED = s1*s2*s3
            
        return np.mean(self.PRED, axis = 0)
        

################################################################################
# ###############################################################################
# ###############################################################################




############# 
# Likelihoods
############# 

class Likelihood:
    """
    abstract class for a likelihood defining a forward step of the model
    """
    
    def __init__(self, pmf, m_step):
        
        self.pmf = pmf 
        self.m_step = m_step
    
class EdgeSampleLikelihood(Likelihood):
    """
    likelihood describing the probability of realizing a set of nodes sampled from a specified edge in Step 1 of the model generation algorithm
    """
    
    def __call__(self, selected, total, **pars):
        
        L = self.pmf(selected, total, **pars) 
        L = np.tril(L)
        np.fill_diagonal(L, 0)
        return L

    def m_step(self, selected, total, chi):
        
        return self.m_step(selected, total, chi)        
        
class NovelNodesLikelihood(Likelihood):
    """
    Likelihood describing the probability of realizing a set of nodes added to an edge from outside the current hypergraph node set in Step 3 of the model generation algorithm. 
    """
    
    def __call__(self, num_novel_nodes, **pars):
        
        L = self.pmf(num_novel_nodes, **pars)
        return np.tril(L) 
    
    def m_step(self, num_novel_nodes, chi):
        return self.m_step(num_novel_nodes, chi)
    
class NodesFromHypergraphLikelihood(Likelihood): 
    """
    Likelihood function describing the probability of realizing a set of nodes added to an edge from the node set of the current hypergraph, excluding the edge sampled in Step 1. Needs to be corrected by num_nodes_to_add ** (-node_counts) if 1/n scaling is used (recommended so that expected number of nodes added in this step is constant as t increases). 
    """
    def __call__(self, num_nodes_to_add, **pars):
        # need to check this
        L = self.pmf(num_nodes_to_add, **pars)
        return np.tril(L)
    
    def m_step(self, num_nodes_to_add, chi):
        return self.m_step(num_nodes_to_add, chi)
